# 25 TFE exercises

#### 1. Import tensorflow package under the name `tf` and enable eager (★☆☆)

In [1]:
import tensorflow as tf
tf.enable_eager_execution()

/Users/i350114/Documents/python_env/pyth3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### 2. Check eager is enabled (★☆☆)

In [2]:
tf.executing_eagerly()

True

#### 3. Show number of GPU (★☆☆)

In [5]:
tfe = tf.contrib.eager
tfe.num_gpus()

0

#### 4.  Create 1D Tensor from 0 to 10 step 2 - [0, 2, 4, 6, 8] (★☆☆)

In [6]:
tf.range(0,10,2)

<tf.Tensor: id=5, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

#### 5.  How to get last 3 elements of 1D Tensor? (★☆☆)

In [7]:
a = tf.range(10)
tf.slice(a,[a.shape.num_elements()-3],[3])

<tf.Tensor: id=11, shape=(3,), dtype=int32, numpy=array([7, 8, 9], dtype=int32)>

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [71]:
b= tf.SparseTensor(indices=[[0, 4]], values=[1], dense_shape=[1, 10])
tf.sparse_tensor_to_dense(b)

<tf.Tensor: id=154, shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int32)>

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [74]:
tf.range(10,50,1)

<tf.Tensor: id=161, shape=(40,), dtype=int32, numpy=
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49], dtype=int32)>

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [83]:
a=tf.range(10)
a[::-1]

<tf.Tensor: id=179, shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [85]:
a=tf.range(9)
tf.reshape(a,shape=(3,3))

<tf.Tensor: id=185, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [120]:
a=tf.constant([1,2,0,0,4,0])
tf.where(a>0)

<tf.Tensor: id=422, shape=(3, 1), dtype=int64, numpy=
array([[0],
       [1],
       [4]])>

#### 11. Create a 3x3 identity matrix (★☆☆)

In [118]:
tf.eye(3)

<tf.Tensor: id=391, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

#### 12. Create a 3x3x3 tensor with random values (★☆☆)

In [127]:
tf.random_normal(shape=(3,3,3))

<tf.Tensor: id=439, shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 0.43048277, -0.0389534 , -0.34340656],
        [ 0.30719113,  0.5165094 , -1.1998122 ],
        [-0.0038675 , -0.84068704,  0.36132345]],

       [[-0.41773742,  0.56132674,  1.9240514 ],
        [ 0.30088416,  0.5185893 , -0.67909664],
        [ 0.17102414, -0.27792045, -0.02785692]],

       [[ 0.8675849 ,  0.23601298, -1.6538779 ],
        [ 0.59168607, -1.9445899 ,  0.34942794],
        [ 0.50351286, -1.2989758 ,  0.3632821 ]]], dtype=float32)>

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [129]:
a=tf.random_normal(shape=(10,10))
tf.reduce_min(a),tf.reduce_max(a)

(<tf.Tensor: id=450, shape=(), dtype=float32, numpy=-1.7399428>,
 <tf.Tensor: id=452, shape=(), dtype=float32, numpy=2.9433608>)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [139]:
a=tf.random_normal(mean=0,shape=(30,))
tf.reduce_mean(a)

<tf.Tensor: id=493, shape=(), dtype=float32, numpy=0.103283755>

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [199]:
a=tf.zeros(shape=(3,3))
paddings = tf.constant([[1, 1],[1,1]])
tf.pad(a, paddings, "CONSTANT",constant_values=1)

<tf.Tensor: id=699, shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [200]:
a=tf.ones(shape=(3,3))
paddings = tf.constant([[1, 1],[1,1]])
tf.pad(a, paddings, "CONSTANT",constant_values=0)

<tf.Tensor: id=704, shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

#### 17. What is the result of the following expression? (★☆☆)

```python
a=tf.constant(0.3)
b=tf.constant(0.1)
c=tf.constant(3,dtype=b.dtype)

print(c*b==a)#?
print(tf.equal(c*b,a)) #?
```

In [14]:
a=tf.constant(0.3)
b=tf.constant(0.1)
c=tf.constant(3,dtype=b.dtype)

print(c*b==a)
print(tf.equal(c*b,a))

False
tf.Tensor(True, shape=(), dtype=bool)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [92]:
diagonal=tf.range(1,5)
b=tf.matrix_diag(diagonal)
paddings = tf.constant([[1,0 ],[0,1]])
tf.pad(b,paddings,"CONSTANT",constant_values=0)

<tf.Tensor: id=740, shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]], dtype=int32)>

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [69]:
max_size = tf.constant(8)
f_row = tf.range(max_size)%2
s_row = tf.range(1,max_size+1)%2
tf.fill([8, 8], 1)*f_row*tf.expand_dims(f_row,axis=1)+ \
    tf.fill([8, 8], 1)*s_row*tf.expand_dims(s_row,axis=1)

<tf.Tensor: id=367, shape=(8, 8), dtype=int32, numpy=
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)>

In [86]:
max_size = tf.constant(8)
f_row = tf.range(max_size)%2
s_row = tf.range(1,max_size+1)%2
X, Y = tf.meshgrid(f_row, s_row)
tf.abs(X-Y)

<tf.Tensor: id=715, shape=(8, 8), dtype=int32, numpy=
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)>

#### 20. Make One Hot Encoding for [0,1,1,0] vector?

In [99]:
indices = [0, 1, 1,0]
tf.one_hot(indices, 2)

<tf.Tensor: id=762, shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)>

#### 21. Get Maximum [5,1,7,3,4,5,6,8,2] of each group, where group indexes are [0,0,0,1,1,2,2,2,2] (★☆☆) result = [7, 4, 8]

In [102]:
tf.segment_max(
    [5,1,7,3,4,5,6,8,2],
    [0,0,0,1,1,2,2,2,2],
)

<tf.Tensor: id=770, shape=(3,), dtype=int32, numpy=array([7, 4, 8], dtype=int32)>

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [111]:
a= tf.random_uniform(shape=(5,5))
Amax, Amin = tf.reduce_max(a), tf.reduce_min(a)
A_normalized = (a - Amin)/(Amax - Amin)
A_normalized

<tf.Tensor: id=844, shape=(5, 5), dtype=float32, numpy=
array([[0.95617944, 0.9455637 , 0.53405035, 0.05748715, 0.5488288 ],
       [0.5545077 , 0.5133231 , 0.4186139 , 0.92421657, 0.19624084],
       [0.7045017 , 0.45809814, 0.13994457, 0.8787952 , 0.9629745 ],
       [0.56902486, 0.10059575, 0.4045165 , 0.21632762, 0.5109138 ],
       [1.        , 0.9575044 , 0.11521755, 0.3483289 , 0.        ]],
      dtype=float32)>

#### 23. Split vector [1,2,3,4,5,6] into 2 parts [1,2,3] and [4,5,6] (★☆☆)

In [115]:
a=tf.constant([1,2,3,4,5,6])
tf.split(a,2)

[<tf.Tensor: id=859, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: id=860, shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [123]:
a = tf.ones((5,3))
b = tf.ones((3,2))
Z = tf.matmul(a,b )
Z

<tf.Tensor: id=890, shape=(5, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]], dtype=float32)>

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [135]:
a=tf.range(11)
tf.where((a<8)&(a>3),-1*a,a)

<tf.Tensor: id=973, shape=(11,), dtype=int32, numpy=array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10], dtype=int32)>

In [21]:
a= tf.range(10)
# a[4:8].assign(tf.zeros(4))

In [19]:
tf.where()

<tf.Tensor: id=11, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>